// Builds a single styled HTML file from the book/ chapters, ready to be printed
// to PDF by a headless browser. Usage:
//   npm install            (in this tools/ folder, once — installs marked)
//   node make-pdf.mjs [outputHtmlPath]
// Then print with Chrome/Edge headless:
//   chrome --headless=new --print-to-pdf=book.pdf --no-pdf-header-footer <outputHtmlPath>
import { marked } from 'marked';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const bookDir = join(here, '..', 'book');
const outHtml = process.argv[2] || join(process.cwd(), 'book.html');

// Reading order for the PDF.
const order = [
  'README.md',
  '00-introduction.md',
  '01-hello.md', '02-header-source.md', '03-inc-src-layout.md',
  '04-menus-library.md', '05-generators-commands.md', '06-cmocka-ctest.md',
  '07-mocking-adc.md', '08-build-options.md', '09-config-header.md',
  '10-lib-plus-lib.md',
  'appendix-a-commands.md', 'appendix-b-cmocka-vs-ctest.md',
  'appendix-c-autogenerated-files.md',
];

// Drop the per-chapter nav footer (the "<- ... -> " link line and its divider),
// which is meaningless in a linear PDF.
function stripNav(md) {
  const lines = md.split(/\r?\n/);
  const out = [];
  for (const l of lines) {
    if (l.includes('](') && (l.includes('←') || l.includes('→'))) continue;
    out.push(l);
  }
  while (out.length && (out[out.length - 1].trim() === '' || out[out.length - 1].trim() === '---')) out.pop();
  return out.join('\n');
}

let body = '';
for (const file of order) {
  const md = stripNav(readFileSync(join(bookDir, file), 'utf8'));
  body += `<section class="chapter">\n${marked.parse(md)}\n</section>\n`;
}

const css = `
:root{--code-bg:#f4f5f7;--border:#d0d5dd;--accent:#2b5797;}
*{box-sizing:border-box;}
@page{margin:18mm 16mm;}
body{font-family:Georgia,'Times New Roman',serif;color:#1a1a1a;line-height:1.55;font-size:11pt;margin:0;}
h1,h2,h3,h4{font-family:'Segoe UI',Arial,sans-serif;line-height:1.25;color:#111;}
h1{font-size:20pt;border-bottom:2px solid var(--accent);padding-bottom:6px;margin-top:0;}
h2{font-size:15pt;margin-top:1.4em;color:var(--accent);}
h3{font-size:12.5pt;margin-top:1.1em;}
p,li{font-size:11pt;}
code{font-family:Consolas,'Courier New',monospace;font-size:9.5pt;background:var(--code-bg);padding:1px 4px;border-radius:3px;}
pre{background:var(--code-bg);border:1px solid var(--border);border-left:3px solid var(--accent);border-radius:5px;padding:10px 12px;overflow:auto;page-break-inside:avoid;}
pre code{background:none;padding:0;font-size:9pt;line-height:1.45;}
table{border-collapse:collapse;width:100%;font-size:10pt;margin:.8em 0;}
th,td{border:1px solid var(--border);padding:5px 8px;text-align:left;vertical-align:top;}
th{background:#eef1f6;}
blockquote{border-left:4px solid var(--border);margin:.8em 0;padding:2px 14px;color:#444;background:#fafbfc;}
a{color:#1a1a1a;text-decoration:none;}
hr{border:none;border-top:1px solid var(--border);margin:1.4em 0;}
.chapter{page-break-before:always;}
.titlepage{height:92vh;display:flex;flex-direction:column;justify-content:center;text-align:center;}
.booktitle{font-size:34pt;border:none;margin:0;}
.subtitle{font-size:13pt;color:#555;font-family:'Segoe UI',sans-serif;max-width:80%;margin:1em auto;}
.repo{font-family:Consolas,monospace;color:#888;margin-top:2em;}
`;

const doc = `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>CMake by Example</title><style>${css}</style></head><body>
<section class="titlepage">
<h1 class="booktitle">CMake by Example</h1>
<p class="subtitle">A step-by-step course &mdash; from a three-line hello world to a multi-library C project with unit tests, mocking, build options, and a generated config header.</p>
<p class="repo">github.com/TalGadasiSolaredge/Cmake_tut</p>
</section>
${body}
</body></html>`;

writeFileSync(outHtml, doc, 'utf8');
console.log('wrote HTML book ->', outHtml);
